version: 0.2
env:
   variables:
       REPOSITORY_URI: "069587973569.dkr.ecr.us-east-1.amazonaws.com/node-app"
       DOCKER_USER: 'web927'
   parameter-store:
       DOCKER_PASS: "DOCKER_PASS"

phases:

  pre_build:
    commands:
    # login to ecr repo
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 069587973569.dkr.ecr.us-east-1.amazonaws.com
      - DOCKER_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -b 1-6)
      - echo $DOCKER_TAG
  build:
  # build image
    commands:
      - echo $DOCKER_USER
      - echo $DOCKER_PASS
      - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin 
      - docker build -t node-app .
      - docker tag node-app:latest $REPOSITORY_URI:$DOCKER_TAG
      - docker tag node-app:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      # push image
      - docker push $REPOSITORY_URI:$DOCKER_TAG
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"node-app","imageUri":"%s"}]' $REPOSITORY_URI:$DOCKER_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json